## discovery server 端口
server:
  discovery:
    port1: 8761
##
eureka:
  instance:
    hostname: 47.111.168.225
  client:
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:${server.discovery.port1}/eureka/
##路由原有的三个服务 骑手、商家、外卖 这里是路由到测试服务地址
spring:
  cloud:
    gateway:
      routes:
        - id: carrierService
          uri: http://courierapi-test.hxfsjt.com/
          predicates:
            - Path=/carrier/**
          filters:
            - ExistedServiceAuthorizationFilter
            - StripPrefix=1
        - id: takeoutService
          uri: http://fswmapi-test.hxfsjt.com/
          predicates:
            - Path=/takeout/**
          filters:
            - ExistedServiceAuthorizationFilter
            - StripPrefix=1
        - id: storeService
          uri: http://fsmsapi-test.hxfsjt.com
          predicates:
            - Path=/store/**
          filters:
            #            - ExistedServiceAuthorizationFilter
            - StripPrefix=1