##当前服务的配置 register.port[\d] 设置 发现微服务的discovery server 端口
server:
  port: 8888
  register:
    port1: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:${server.register.port1}/eureka/

path:
  oauth:
    prefix: oauth

spring:
  application:
    name: spring-cloud-gateway
  profiles:
    active: test
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: firstmicroservice
          uri: lb://service-demo/product/
          predicates:
            - Path=/product/**
        #        filters:
        #        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - id: authservice
          uri: lb://service-auth/oauth
          predicates:
            - Path=/${path.oauth.prefix}/**

# rate limiter configuration

rate-limit:
  bucket:
    capacity: 30
    refillTokens: 2
    refillDuration: 1