##当前服务的配置 register.port[\d] 设置 发现微服务的discovery server 端口
server:
  port: 8888
  register:
    port1: 8761

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:${server.register.port1}/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: firstmicroservice
        uri: lb://firstmicroservice/hello
        predicates:
        - Path=/hello
        filters:
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      - id: authservice
        uri: lb://authservice/oauth
        predicates:
        - Path=/oauth/**